---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - ruby
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.py"
  - "**.scss"
exclude_paths:
  - "**/*.min.js"
  - "**/*.min.css"
