language: ruby
rvm:
- 2.1
node_js:
- '4'

before_install:
- export TZ=America/Bogota
- node --version
- nvm --version
install:
  - gem install bundler
  - bundle install
  - npm install
  - npm install -g bower gulp
  - bower install

script:
 - gulp compile --harmony
 - jekyll build
 - scss-lint ./_sass
 - htmlproofer ./_site --disable-external

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  bundler: true
  directories:
    - bower_components
    - node_modules

sudo: false
