language: ruby
rvm:
- 2.1

before_install:
- export TZ=America/Bogota

install:
  - gem install bundler
  - bundle install
  - npm install
  - npm install -g bower gulp
  - bower install

script:
 - date
 - gulp compile
 - jekyll build
 - scss-lint ./_sass
 - htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  bundler: true
  directories:
    - bower_components
    - node_modules

sudo: false
