language: ruby
rvm:
- 2.1
 
install: gem install jekyll html-proofer jekyll-sitemap
script: jekyll build && htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 

sudo: false 
