language: ruby
rvm:
- 2.5
node_js:
- '8'

before_install:
- export TZ=America/Bogota
- nvm install node
- node --version
- nvm --version

install:
  - gem install bundler
  - bundle install
  - npm install
  - npm install -g eslint

script:
 - jekyll build
 - npm run test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  bundler: true
  directories:
    - node_modules

sudo: false
