language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install:
    - "pip install Lektor"
before_script:
    - npm install -g bower
    - npm install
    - bower install
    - gulp compile
script: "lektor build && lektor deploy ghpages"
