language: ruby
rvm:
- 2.1
 
install: gem install jekyll html-proofer jekyll-sitemap
script: jekyll build && htmlproofer ./_site

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 

sudo: false 
