language: ruby
rvm:
- 2.1
 
install: gem install bundler
script: 
 - bundle install
 - jekyll build
 - scss-lint ./_sass

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 

sudo: false 
