# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Scot3004
email: scot3004@gmail.com
description:  Sitio de presentación Sergio Orozco Torres - Desarrollador web
nombre: Sergio C. Orozco Torres
lema: Renovarse refleja la adaptación al cambio
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.scot3004.xyz" # the base hostname & protocol for your site
twitter_username: scot3004
github_username: scot3004

# Build settings
markdown: kramdown

exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "resources"
  - "nbproject"
